### PR TITLE
feature/identifier

### PR DESCRIPTION
**Pull request by rhayes777**
Customise what attributes are used to create an identifier. Only attributes of an object found in __identifier_fields__ are used if it is defined.

Currently no attributes of any search are used because an example __identifier_fields__ is defined in AbstractSearch.

This should be replaced with:

```python
__identifier_fields__ = ("include", "these", "attributes")

### CODE REVIEW

**Comment by rhayes777** [comment]
@jonathanfrawley Presumably if we run the build for every push it doesn't need to also run for PRs?

**Comment by jonathanfrawley** [comment]
Yeah, it's up to you. I think it is nice to see the status in pull requests personally so you could remove the push hook if that suits best.

**Comment by rhayes777** [comment]
I'd prefer to leave push rather than pull just so you get feedback more frequently. Easier to identify a problem if it was introduced more recently

**Comment by rhayes777** [comment]
The status actually shows in the PR for any checks run on that commit I think

**Comment by jonathanfrawley** [comment]
Ah okay, in that case feel free to remove.

**Review by Jammy2211 — APPROVED** [review]

**Pull request merged**
