### PR TITLE
feature/grid search result

### LINKED ISSUE #855: GirdSearchResult Redesign
A non-linear search of searches outputs a `GridSearchResult` as a .pickle file here:

```
        def save_results():
            self.paths.save_object(
                "result",
                builder()
            )
```

The results are output to a dedicated `files` folder in the grid search:

image

We should update this so that all quantities are output to human readable formats (e.g. .json).

**Reducing File Size**

An issue with the `GridSearchResult` is that it includes the list of `Result` objects for every cell in a grid search. This includes attributes which take up a lot of disk space (e.g. the `Samples` object).

For picking / output they take up too much disk space (and are accessible via the aggregator anyway).

However, certain `GridSearchResult` properties use attributes in the `results`. However, it only uses information contained in the `SamplesSummary` object. 

Therefore, can we also refactor the `GridSearchResult` to not take as input `results` but instead a `samples_summary_list`.

**Integration Test**

The following script has assertions which include attributes which use the `Samples`, so should help fixing the code:

https://github.com/Jammy2211/autofit_workspace_test/blob/main/scripts/database/scrape/grid_search.py

### PR DESCRIPTION
**Pull request by rhayes777**
Resolves #855

GridSearchResult now comprises SamplesSummaries
GridSearchResult is persisted as a JSON

### CODE REVIEW

**Comment by Jammy2211** [comment]
This script:

https://github.com/Jammy2211/autofit_workspace_test/blob/main/scripts/database/scrape/grid_search.py

Produces this error:

```
2023-10-27 10:49:52,020 - autofit.database.aggregator.aggregator - INFO - 1 fit(s) found matching query
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autofit_workspace_test/scripts/database/scrape/grid_search.py", line 167, in <module>
    print(f"{list(agg.grid_searches())[0]['result'].best_result}\n")
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/grid_search/result.py", line 111, in __getattr__
    return getattr(self.best_samples, item)
AttributeError: 'SamplesSummary' object has no attribute 'best_result'
```

**Comment by rhayes777** [comment]
best_result needs to be renamed best_samples

**Comment by Jammy2211** [comment]
So running an autolens grid search test:

https://github.com/Jammy2211/autolens_workspace_test/blob/main/scripts/database/scrape/slam_subhalo.py

I now realise the use of a `Result` did have another purpose, as it was also used for prior passing:

```
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/scripts/database/scrape/slam_subhalo.py", line 195, in <module>
    subhalo_results = slam.subhalo.detection(
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/subhalo.py", line 182, in detection
    subhalo.mass.centre = subhalo_result.model_absolute(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/grid_search/result.py", line 111, in __getattr__
    return getattr(self.best_samples, item)
AttributeError: 'SamplesSummary' object has no attribute 'model_absolute'
```

We definitely need this functionality.

These look like methods we can just define in the `Samples` object and have the `Result` object call:

```
    def model_absolute(self, a: float) -> AbstractPriorModel:
        """
        Parameters
        ----------
        a
            The absolute width of gaussian priors

        Returns
        -------
        A model mapper created by taking results from this search and creating priors with the defined absolute
        width.
        """
        return self.model.mapper_from_gaussian_tuples(
            self.samples.gaussian_priors_at_sigma(sigma=self.sigma), a=a
        )

    def model_relative(self, r: float) -> AbstractPriorModel:
        """
        Parameters
        ----------
        r
            The relative width of gaussian priors

        Returns
        -------
        A model mapper created by taking results from this search and creating priors with the defined relative
        width.
        """
        return self.model.mapper_from_gaussian_tuples(
            self.samples.gaussian_priors_at_sigma(sigma=self.sigma), r=r
        )
```

**Comment by rhayes777** [comment]
Done. At this rate Samples will become what Result was

**Comment by Jammy2211** [comment]
```
emoving all files except for .zip file
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/scripts/database/scrape/slam_subhalo.py", line 195, in <module>
    subhalo_results = slam.subhalo.detection(
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/subhalo.py", line 195, in detection
    clumps=al.util.chaining.clumps_from(result=subhalo_result, mass_as_model=True),
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoGalaxy/autogalaxy/analysis/chaining_util.py", line 231, in clumps_from
    clumps = result.instance.clumps.as_model((MassProfile,))
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/grid_search/result.py", line 111, in __getattr__
    return getattr(self.best_samples, item)
AttributeError: 'SamplesSummary' object has no attribute 'instance'
```

**Comment by Jammy2211** [comment]
> Done. At this rate Samples will become what Result was

It is common for projects to use inheritance to customize the `Result` a lot:

```
class ResultImaging(ResultDataset):
    """
    After the non-linear search of a fit to an imaging dataset is complete it creates this `ResultImaging`, object
    which includes:

    - The samples of the non-linear search (E.g. MCMC chains, nested sampling samples) which are used to compute
      the maximum likelihood model, posteriors and other properties.

    - The model used to fit the data, which uses the samples to create specific instances of the model (e.g.
      an instance of the maximum log likelihood model).

    - The non-linear search used to perform the model fit.

    This class contains a number of methods which use the above objects to create the max log likelihood `Plane`,
    `FitImaging`, adapt-galaxy images,etc.

    Parameters
    ----------
    samples
        A PyAutoFit object which contains the samples of the non-linear search, for example the chains of an MCMC
        run of samples of the nested sampler.
    model
        The PyAutoFit model object, which includes model components representing the galaxies that are fitted to
        the imaging data.
    search
        The non-linear search used to perform this model-fit.

    Returns
    -------
    ResultImaging
        The result of fitting the model to the imaging dataset, via a non-linear search.
    """

    @property
    def max_log_likelihood_fit(self) -> FitImaging:
        """
        An instance of a `FitImaging` corresponding to the maximum log likelihood model inferred by the non-linear
        search.
        """
        return self.analysis.fit_imaging_via_instance_from(
            instance=self.instance,
        )

    @property
    def max_log_likelihood_tracer(self) -> Tracer:
        """
        An instance of a `Tracer` corresponding to the maximum log likelihood model inferred by the non-linear search.

        The `Tracer` is computed from the `max_log_likelihood_fit`, as this ensures that all linear light profiles
        are converted to normal light profiles with their `intensity` values updated.
        """

        return (
            self.max_log_likelihood_fit.model_obj_linear_light_profiles_to_light_profiles
        )
```

But I agree, moving all prior-passing functionality to `Samples` (or making a class which `Samples` uses via composition) to handle prior passing explicitly, separate from the `Result`, seems like a sensible plan.

**Review by Jammy2211 — APPROVED** [review]

**Pull request merged**
