### PR TITLE
feature/mapper by path

### PR DESCRIPTION
**Pull request by rhayes777**
Recovery of model instances from samples relied on prior ordering. Now it uses the name of the prior. This is still a bit dodgy but backwards compatible.

That is, a prior with path model.sub_model.prior gets a name model_sub_model_prior in samples. This is matched back to the path. The risk is that (in theory) two priors could have the same effective name. However, this would have been an issue regardless.

The better solution is to change kwargs to use paths instead of strings. I'm concerned this will break backwards compatibility but I'm going to try it...

### CODE REVIEW

**Comment by rhayes777** [comment]
Ok integrated and tested - it seems to respect backwards compatability and eliminate the issue posed in the example.py

**Comment by rhayes777** [comment]
It uses the best possible method available - for backwards compatability it will match to names, but in future the keys in the sample.kwargs dictionary are paths. This is much safer. Still warrants testing obviously.

**Comment by Jammy2211** [comment]
I look forward to breaking this.

**Comment by rhayes777** [comment]
:'(

**Review by Jammy2211 — APPROVED** [review]

**Pull request merged**
