### PR TITLE
feature/sensitivity mask

### LINKED ISSUE #1058: Masked Sensitivity Mapping
The following example script runs sensitivity mapping for a strong lens:

https://github.com/Jammy2211/autolens_workspace_test/blob/main/slam/integration/source_lp/mass_total/sensitivity.py

It performs a 2 x 2 sensitivity grid, in order to run fast.

At the end, I have added a new input the `sensitivity_mask`, which signifies that only one of the four grid cells should run (in autolens convention `True` means to ignore).

```
    subhalo_result = slam.subhalo.sensitivity_imaging_lp.run(
        settings_search=settings_search,
        mask=mask,
        psf=dataset.psf,
        adapt_images=al.AdaptImages.from_result(result=source_lp_result),
        mass_result=mass_result,
        subhalo_mass=af.Model(al.mp.NFWMCRLudlowSph),
        grid_dimension_arcsec=3.0,
        number_of_steps=2,
        sensitivity_mask=[[True, True], [True, False]],
    )
```

On the following PyAutoFit branch I got the sensitivity map to successfully only run 1 in 4 times:

https://github.com/rhayes777/PyAutoFit/tree/feature/sensitivity_mask

The main edit was here:

https://github.com/rhayes777/PyAutoFit/blob/feature/sensitivity_mask/autofit/non_linear/grid/sensitivity/__init__.py

```
    def _make_jobs(self) -> Generator[Job, None, None]:
        """
        Create a list of jobs to be run on separate processes.

        Each job fits a perturb image with the original model
        and a model which includes a perturbation.
        """
        for number, (perturb_instance, perturb_model, label) in enumerate(
            zip(self._perturb_instances, self._perturb_models, self._labels)
        ):

            shape_index = self.shape_index_from_number(number=number)

            should_bypass = False

            if self.mask is not None:
                should_bypass = np.asarray(self.mask)[shape_index]

            if not should_bypass:

                if self.perturb_model_prior_func is not None:
                    perturb_model = self.perturb_model_prior_func(
                        perturb_instance=perturb_instance, perturb_model=perturb_model
                    )

                simulate_instance = copy(self.instance)
                simulate_instance.perturb = perturb_instance

                paths = self.paths.for_sub_analysis(
                    label,
                )

                yield self.job_cls(
                    simulate_instance=simulate_instance,
                    model=self.model,
                    perturb_model=perturb_model,
                    base_instance=self.instance,
                    simulate_cls=self.simulate_cls,
                    base_fit_cls=self.base_fit_cls,
                    perturb_fit_cls=self.perturb_fit_cls,
                    paths=paths,
                    number=number,
                )
```

The code is set up to retain the overall grid information of the sensitivity map, for example, with this mask the job that does run is still job number 3, as seen in `results.csv`:

```
index,centre_0,centre_1,log_evidence_increase,log_likelihood_increase
    3,     1.5,     1.5,  -1613.7677295368567,    -1613.7677295368567
```

This is important so that I could change the mask and run more cells in the sensitivity map without issue, and to in general retain the sensitivity map structure.

The problem is that the `SensitivityResult` currently does not support a mask input, and calling any of its methods after a mask is used raises an exception:

```
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/integration/source_lp/mass_total/sensitivity.py", line 356, in <module>
    fit()
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/integration/source_lp/mass_total/sensitivity.py", line 342, in fit
    subhalo_result = slam.subhalo.sensitivity_imaging_lp.run(
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/subhalo/sensitivity_imaging_lp.py", line 626, in run
    subhalo_util.visualize_sensitivity(
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/subhalo/subhalo_util.py", line 142, in visualize_sensitivity
    plotter.subplot_figures_of_merit_grid()
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/lens/sensitivity.py", line 367, in subplot_figures_of_merit_grid
    figures_of_merit = self.result.figure_of_merit_array(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/lens/sensitivity.py", line 133, in figure_of_merit_array
    return self._array_2d_from(values=figures_of_merits)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/lens/sensitivity.py", line 89, in _array_2d_from
    values_reshaped = [value for values in values.native for value in values]
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/grid_list.py", line 75, in native
    return np.reshape(np.array(self), self.shape)
  File "/home/jammy/venvs/PyAuto/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 285, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/jammy/venvs/PyAuto/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 1 into shape (2,2)
```

Can you do the following:

1) Make sure you agree that my implementation of the mask is the best way to do it, and refactor as you please.
2) Update `SensitvityResult` so that its attributes still work when a `mask` is input.

An example `SensitivityResult` attribute is the log evidence of the `base` run of every grid on the sensitivity map:

```

    @property
    @as_grid_list
    def log_evidences_base(self) -> GridList:
        """
        The log evidences of the base model for each sensitivity fit
        """
        return [sample.log_evidence for sample in self.samples]
```

The problem is that `self.samples` is no longer a list of 4 entries but fewer than 4 entries, depending on how the mask sets up the shape.

I think we basically need the `GridList` object to account for the mask when doing this mapping, and to do so in such a way that all masked entries in `log_evidences_base` become None.

https://github.com/rhayes777/PyAutoFit/blob/feature/sensitivity_mask/autofit/non_linear/grid/grid_list.py

### PR DESCRIPTION
**Pull request by rhayes777**
Resolves #1058

### CODE REVIEW

**Comment by Jammy2211** [comment]
A consequence of the masked result is that code which uses the result no longer works, as expected.

For example, autolens uses the following code to get the y coordinate of every subhalo:

```
    @property
    def y(self) -> List[float]:
        """
        The y coordinates of the physical values of the subhalo grid, where each value is the centre of a grid cell.

        These are the `centre` coordinates of the dark matter subhalo priors.
        """
        return self.physical_centres_lists_from(
            path="galaxies.subhalo.mass.centre.centre_0"
        )
```

This now gives an error because certain `Samples` objects are None in the autofit code called:

```
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/integration/source_lp/mass_total/sensitivity.py", line 357, in <module>
    fit()
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/integration/source_lp/mass_total/sensitivity.py", line 342, in fit
    subhalo_result = slam.subhalo.sensitivity_imaging_lp.run(
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/subhalo/sensitivity_imaging_lp.py", line 798, in run
    subhalo_util.visualize_sensitivity(
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/subhalo/subhalo_util.py", line 136, in visualize_sensitivity
    mat_plot_2d = aplt.MatPlot2D(axis=aplt.Axis(extent=result.extent), output=output)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/lens/sensitivity.py", line 66, in extent
    return (np.min(self.x), np.max(self.x), np.min(self.y), np.max(self.y))
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/lens/sensitivity.py", line 57, in x
    return self.perturbed_physical_centres_list_from(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/sensitivity/result.py", line 43, in perturbed_physical_centres_list_from
    return self._physical_centres_lists_from(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/grid_list.py", line 36, in wrapper
    values = func(grid_search_result, *args, **kwargs)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/grid_search/result.py", line 69, in _physical_centres_lists_from
    return [value_for_samples(samples) for samples in samples]
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/grid_search/result.py", line 69, in <listcomp>
    return [value_for_samples(samples) for samples in samples]
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/grid_search/result.py", line 61, in value_for_samples
    return samples.model.object_for_path(path).mean
AttributeError: 'NoneType' object has no attribute 'model'
```

The code raising the error is this:

```
        if isinstance(path, str):
            path = path.split(".")

            def value_for_samples(samples):
                return samples.model.object_for_path(path).mean

        else:
            paths = [p.split(".") for p in path]

            def value_for_samples(samples):
                return tuple(samples.model.object_for_path(p).mean for p in paths)

        return [value_for_samples(samples) for samples in samples]
```

There is a similar issue where the result is None but when code which calls the `log_evidence`'s of the sensitivity map is caleld, it causes a bug:

```
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/sensitivity/result.py", line 82, in log_evidence_differences
    self.log_evidences_perturbed, self.log_evidences_base
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/grid_list.py", line 36, in wrapper
    values = func(grid_search_result, *args, **kwargs)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/sensitivity/result.py", line 71, in log_evidences_perturbed
    return [sample.log_evidence for sample in self.perturb_samples]
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/sensitivity/result.py", line 71, in <listcomp>
    return [sample.log_evidence for sample in self.perturb_samples]
AttributeError: 'NoneType' object has no attribute 'log_evidence'
```

Could we make it so that every masked sensitivity grid cell is given a `NullSamples` object, which has the following:

1) The `model`, so that the above code still works even though the fit is bypasssed.
2) A `log_evidence` and `log_likelihood` of zero, which I think is a sensible enough default value.

**Comment by rhayes777** [comment]
Done

**Comment by Jammy2211** [comment]
The `model` object is there but could we have it also include the `perturb`?

```
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/integration/source_lp/mass_total/sensitivity.py", line 357, in <module>
    fit()
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/integration/source_lp/mass_total/sensitivity.py", line 342, in fit
    subhalo_result = slam.subhalo.sensitivity_imaging_lp.run(
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/subhalo/sensitivity_imaging_lp.py", line 798, in run
    subhalo_util.visualize_sensitivity(
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/slam/subhalo/subhalo_util.py", line 136, in visualize_sensitivity
    mat_plot_2d = aplt.MatPlot2D(axis=aplt.Axis(extent=result.extent), output=output)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/lens/sensitivity.py", line 66, in extent
    return (np.min(self.x), np.max(self.x), np.min(self.y), np.max(self.y))
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoLens/autolens/lens/sensitivity.py", line 57, in x
    return self.perturbed_physical_centres_list_from(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/sensitivity/result.py", line 43, in perturbed_physical_centres_list_from
    return self._physical_centres_lists_from(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/grid_list.py", line 36, in wrapper
    values = func(grid_search_result, *args, **kwargs)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/grid_search/result.py", line 69, in _physical_centres_lists_from
    return [value_for_samples(samples) for samples in samples]
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/grid_search/result.py", line 69, in <listcomp>
    return [value_for_samples(samples) for samples in samples]
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/grid_search/result.py", line 61, in value_for_samples
    return samples.model.object_for_path(path).mean
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/model.py", line 186, in object_for_path
    instance = getattr(instance, name)
AttributeError: 'Collection' object has no attribute 'perturb'
```

**Comment by Jammy2211** [comment]
So I think the issue is a `SensitivityResult` has two methods:

```
    def perturbed_physical_centres_list_from(
        self, path: Union[str, Tuple[str, ...]]
    ) -> GridList:
        """
        Returns the physical centres of the perturbed model for each sensitivity fit

        Parameters
        ----------
        path
            The path to the physical centres in the samples
        """
        return self._physical_centres_lists_from(
            self.perturb_samples,
            path,
        )
```

```
    # noinspection PyTypeChecker
    @as_grid_list
    def physical_centres_lists_from(
        self,
        path: Union[str, Tuple[str, ...]],
    ) -> GridList:
        """
        Get the physical centres of the grid search from a path to an attribute of the instance in the samples.

        Parameters
        ----------
        path
            The path to the attribute to get from the instance

        Returns
        -------
        A list of lists of physical values
        """
        return self._physical_centres_lists_from(self.samples, path)
```

I think as long as the `model` includes the `perturb` they should all work.

**Comment by rhayes777** [comment]
Added. I guess the two options are we carry on mocking the same interface or we could consider if there's an elegant way to account for masking in downstream functions?

**Comment by Jammy2211** [comment]
The values coming from `perturbed_physical_centres_list_from` are still zero'd at masked values.

However, they come from the `model` and as far as I can tell should still be computable via this function:

```
        if isinstance(path, str):
            path = path.split(".")

            def value_for_samples(samples):
                return samples.model.object_for_path(path).mean

        else:
            paths = [p.split(".") for p in path]

            def value_for_samples(samples):
                return tuple(samples.model.object_for_path(p).mean for p in paths)
```

Just because we apply a mask and skip the fit, the perturb `model` can still be set up with a prior for these values allowing the function above to return a non-zero value, I think?

Basically, to produce 2D images of the sensitivity result for autolens, I need to know the x and y coordinates of where the sensitivity mapping of a dark matter subhalo took place (including cells which were bypassed via a mask). I don't think there is a general way I can do this (e.g. independent of how the sensitivity grid was set up) without calling:

 ```
    @property
    def y(self) -> af.GridList:
        """
        The y coordinates of the physical values of the sensitivity mapping grid.

        These are the `centre` coordinates of the dark matter subhalos that are included in the simulated datasets.
        """
        return self.perturbed_physical_centres_list_from(
            path="perturb.mass.centre.centre_0"
        )

    @property
    def x(self) -> af.GridList:
        """
        The x coordinates of the physical values of the sensitivity mapping grid.

        These are the `centre` coordinates of the dark matter subhalos that are included in the simulated datasets.
        """
        return self.perturbed_physical_centres_list_from(
            path="perturb.mass.centre.centre_1"
        )
```

**Comment by Jammy2211** [comment]
I could, for example, extract this information from some of the internal sensitivty mapping arrays, but if the parameter ordering were swapped by the user this calculation would no longer work correctly, so it needs to work on the model path.

**Comment by rhayes777** [comment]
Could you not simply check whether a result is a MaskedJobResult and skip setting the associated values in that case?

**Comment by rhayes777** [comment]
It looks as though these perturbed values are being respected for masked results

```python
def test_physical_centres_lists(masked_result, masked_sensitivity):
    assert masked_result.perturbed_physical_centres_list_from("perturb.centre") == [
        0.25,
        0.25,
        0.25,
        0.25,
        0.75,
        0.75,
        0.75,
        0.75,
    ]
```

When prior limits were updated for perturbed models this was not updating the underlying message for Uniform and LogGaussian priors causing the mean to be the same for every perturb model inspite of the priors differing. Was this the cause of the issue?

**Comment by rhayes777** [comment]
The perturbed_physical_centres_list_from now takes values directly from the sensitivity map result. No need to specify 'perturb'.

e.g.
```python
masked_result.perturbed_physical_centres_list_from("centre")

**Pull request merged**
