### PR TITLE
fix test causing build to fail because a message cannot be pickled

### PR DESCRIPTION
**Pull request by rhayes777**

### CODE REVIEW

**Comment by Jammy2211** [comment]
This actually stops actual Dynesty runs from working lol

**Comment by rhayes777** [comment]
Hmm will try and solve the underlying issue

**Comment by rhayes777** [comment]
Ah I see so you readd it after. I guess that's a solution

**Comment by Jammy2211** [comment]
There was no underlying issue we literally removed dynesty's likelihood function lol

**Comment by rhayes777** [comment]
I mean as in when using dill to serialise a factor

**Pull request merged**
